name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LANGUAGE: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_COMMIT: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "True"
          SHOW_TITLE: "True"
          SHOW_LOC_CHART: "True"


          SHOW_TOTAL: "True"

          TIME_RANGE: "last_30_days"
          LANG_COUNT: "8"

          BLOCKS: "⣿"
          CODE_LANG: "txt"

          IGNORED_LANGUAGES: "Binary YAML JSON TOML"